### ISSUE TITLE
Add ArviZ to showcase (alongside Mistic)

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh.org#19]
[The ArviZ team is 👍 ](https://github.com/arviz-devs/arviz/discussions/1883)

Copy:

>ArviZ is a community-led package for exploratory analysis of Bayesian models in Python.

>It Includes functions for posterior analysis, data storage, sample diagnostics, model checking, and comparison. The goal is to provide backend-agnostic tools for diagnostics and visualizations of Bayesian inference.

GIF:
![arviz](https://user-images.githubusercontent.com/33131404/137769634-69679454-a0b7-442b-9d19-a25e7053a649.gif)

cc @bryevdv

**Comment by bryevdv** [comment]
For Mistic:

> [Mistic](https://github.com/MathOnco/Mistic) is a software package written in Python and uses the visualization library Bokeh. Mistic can be used to simultaneously view multiple multiplexed 2D images using pre-defined coordinates (e.g. t-SNE or UMAP), randomly generated coordinates, or as vertical grids to provide an overall visual preview of the entire multiplexed image dataset. Code: [MathOnco/Mistic](https://github.com/MathOnco/Mistic).


![d627c344ec7d28686476fe2eb2262826cad3efcf_2_690x360](https://user-images.githubusercontent.com/1078448/139540955-9cdfe9f6-bbea-464d-b80c-b428a5cee88f.jpeg)

**Comment by pavithraes** [comment]
@bryevdv Thanks for the notes and the description! I'll add these now :)
